### ISSUE TITLE
Bump jsonwebtoken from 8.5.1 to 9.0.0 needed

### ISSUE THREAD

**Issue by madaher-dev** [stefanprokopdev/verify-apple-id-token#152]

**Comment by stefanprokopdev** [comment]
Hey @madaher-dev :wave: Thanks for creating the issue! If you have an active project, where you can test everything, you can open a PR with the suggested change :slightly_smiling_face:

**Comment by madaher-dev** [comment]
Hi @stefanprokopdev 
There is already a PR pending merge

**Comment by stefanprokopdev** [comment]
True, but not finished .. the pipeline checks was not successful.

**Comment by ilnicki** [comment]
@stefanprokopdev I've created PR with successful checks.

**Comment by stefanprokopdev** [comment]
Thank you so much @ilnicki :heart: You can install the patched version :rocket: 

And happy new year guys! :tada:
