### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'header')

### ISSUE THREAD

**Issue by levanchien** [stefanprokopdev/verify-apple-id-token#161]
Hello,
I tried version: "^3.0.1",
I got this
TypeError: Cannot read properties of null (reading 'header')
      at E:\WorkSpace\mitech\backend\node_modules\verify-apple-id-token\src\lib\verifyAppleIdToken.ts:26:32
      at step (node_modules\verify-apple-id-token\dist\lib\verifyAppleIdToken.js:33:23)
      at Object.next (node_modules\verify-apple-id-token\dist\lib\verifyAppleIdToken.js:14:53)

**Comment by stefanprokopdev** [comment]
Hey @levanchien :wave: 

Thanks for creating a new issue. Can you please describe what was the problem or how did you solve it? Maybe someone will face the same problem in the future :pray:

**Comment by levanchien** [comment]
Hi @stefanprokopdev.
Sorry. I think it's okay. I tried it with a fake idToken string and got that error message.
