### ISSUE TITLE
Feature: Support multiple AUD

### ISSUE THREAD

**Issue by sergioisidoro** [stefanprokopdev/verify-apple-id-token#203]
When we have android apps or web clients, we are expected to generate a new identifier for each client. 
This means that the AUD can actually be a list of clients that are valid.

We can do this as a work arround:
```.js
  let jwtClaims

  await Promise.all(["CLIENT_A", "CLIENT_B", "CLIENT_C"].map(async (clientId) => {
    try {
      jwtClaims =  await verifyToken({
          idToken: idToken,
          clientId: clientId
        });
    } catch (error) {
      // Lets not do anything
    }
  }))

  if(!jwtClaims) {
    // Explode! ...
  }
 ```
But that's a but dirty.

It seems that it should only take a few lines to make this support multiple AUDs.
```.ts
  const isFounded = []
    .concat(jwtClaims.aud)
    .some((aud) => [].concat(params.clientId).includes(aud));
```

**Comment by stefanprokopdev** [comment]
Hello @sergioisidoro :wave: 

thanks for creating the issue. It looks good to me. Could you please create a PR with this change? :pray:

**Comment by sergioisidoro** [comment]
Will give it a go :)

**Comment by sergioisidoro** [comment]
I'm so sorry for wasting your time. It must have been a long day when I created this issue.
ClientId is already a string or an Array of strings, and this functionality is already implemented and tested...

```
 jwtClaims =  await verifyToken({
          idToken: idToken,
          clientId: ["CLIENT_A", "CLIENT_B", "CLIENT_C"]
        });
```
Works 🤦

I created a pull request instead with additional documentation, so this would not be a full waste of time for you 😅
https://github.com/stefanprokopdev/verify-apple-id-token/pull/205

**Comment by stefanprokopdev** [comment]
No problem :slightly_smiling_face: thanks for the PR!
